version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install

  lint:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:18.17
    parallelism: 2
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run tests in parallel
          command: |
            TEST_FILES=$(circleci tests glob "tests/**/*.test.js" | circleci tests split)
            for file in $TEST_FILES; do
              echo "Running $file"
              node $file
            done

  notify:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Send Slack notification
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Pipeline finalizado correctamente"}' \
            $SLACK_WEBHOOK

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires: [build]
      - test:
          requires: [build]
      - notify:
          requires: [lint, test]

